### ISSUE TITLE
Cleanup the Platforms.java class

### ISSUE THREAD

**Issue by nadvolod** [saucelabs/simple_sauce#108]
At some point early on we introduced this `Platforms.java` class which is causing me a lot of confusion. For example, it does:
`Platforms.WINDOWS_10` which returns "Windows 10"
But then it also does `Platforms.windowsLatest()` which returns another Windows string
I think that the way we use this class should be at least consistent:

- We should probably replace `Platforms.windowsLatest()` with `Platforms.WINDOWS_LATEST` which would look like this
`WINDOWS_LATEST("Windows 10")`,

Also, it has the capability to do `Platforms.MAC_OS.MOJAVE` but doesn't have the same capability for Windows. If we go this route, which I like, then we should add an option to do `Platforms.Windows.WindowsOptionHere`

**Comment by picimako** [comment]
Hi @nadvolod,
I looked into this issue and as I see the `Platforms.java` class no longer exists. I guess it has already been removed/refactored?
