### ISSUE TITLE
Rename the bindings

### ISSUE THREAD

**Issue by nadvolod** [saucelabs/simple_sauce#128]
This will also involve renaming items in the code and likely fixing CI Pipelines

**Comment by joshmgrant** [comment]
Please see #132 for the Python case of this

**Comment by nadvolod** [comment]
@joshmgrant so can we remove the Ruby tag here?

**Comment by titusfortner** [comment]
Merged the Ruby code;
Java PR: #138 
Looks like Python is already removed
