### ISSUE TITLE
Test name in Sauce is set to 'null' when SauceOptions() are passed into SauceSession()

### ISSUE THREAD

**Issue by nadvolod** [saucelabs/simple_sauce#144]
Looks like the following code creates a test titled 'null' when we pass in an empty options objects into SauceSession.
```
        SauceOptions options = new SauceOptions();
        session = new SauceSession(options);
        RemoteWebDriver driver = session.start();
```

**Comment by picimako** [comment]
@nadvolod 
Is this related to the `name` configuration option not having a default value, or not being validated before starting a session?

**Comment by titusfortner** [comment]
@nadvolod where are you seeing "null?" If nothing is specified, you get the standard default Sauce name like - `Unnamed job b99564f9483b432385a6e1b5dfcf312f`

**Comment by nadvolod** [comment]
@titusfortner this might have been me messing something up somewhere. I can't reproduce it.
