### ISSUE TITLE
Need way to specify latest browser versions without releasing new code

### ISSUE THREAD

**Issue by mmerrell** [saucelabs/simple_sauce#17]
At the moment, the various languages each hard-code browser versions like "Firefox 67.0" and "Chrome 75.0" right there in the code. Understanding that this was not meant to be permanent, it's time to start thinking about how to make these frameworks more self-sufficient.

Initial requirements:
- All the language bindings use the same mechanism, and ideally read from the same "cache"
- Browser versions come from config, not from code, likely either yaml or JSON that's generated by a query to a web service
- Poll the Platform Configurator (or some other tool) to generate the currently-supported versions of each browser
- The code will read this cache file, taking the most recent browser as "latest" and running that by default
- Users will need to be able to override the version
- The file can't be generated every time you run a test. It would either be at the beginning of a build, or the Web Service needs to indicate, probably via CRV check, whether or not the info has changed
- This call to the web service has to be very tolerant of failure--if it fails, there must be some way to use another resource, either a JSON/yaml that we package with each version (which we'll try to keep up-to-date), or some set of fall-backs. This call CANNOT prohibit the execution of tests, nor can it create any impediment to starting a test

There are probably more, but the main idea is that we have to get out of the business of hand-maintaining browser versions. This is NOT a requirement for a beta, but I'll be watching closely to make sure such a feature can be incorporated into the various bindings.

**Comment by nadvolod** [comment]
I'm cool with this idea. What I want to make sure doesn't happen is that we open up possibilities for users to start passing strings again. I want zero interactions with the Platform Configurator and I want the IDE to guide the user into the correct available platform capabilities. So, almost everything statically typed and avoiding strings. This is my biggest pain and complaint about all remote grid interactions. That even as an SA, I never have any idea about what strings to pass to what properties to create a proper capabilities object. I've dealt with this pain for years with Sauce and Browser Stack and I'd like it to stop 🛑 :) W3C is a perfect example. I have no clue what works and what doesn't until I try the code and debug for hours. Even our docs are useless. But our code could be the source of truth 😊

**Comment by titusfortner** [comment]
Can't we just use 'latest' to get this functionality? And set that to be the default?

**Comment by titusfortner** [comment]
That said, I have a spike in the Ruby code that creates cache from API, looks for requested info from it and if it can't find it, does an API call in case the cache is outdated. Wasn't fully functional, but I think that's the same idea as here.

**Comment by mmerrell** [comment]
Yeah, it's the same idea. I think there's a way to greatly improve things, and also keep users from having to guess or use the Platform Configurator... we just haven't thrown much effort behind that yet.

**Comment by joshmgrant** [comment]
Using `latest` will work across all supported browsers as a "reasonable default". There is some quirkiness with Safari/Mac but this will work.

**Comment by titusfortner** [comment]
Since we do have a way of specifying latest browser, I'm opening a new ticket #151 that represents the other pieces of this conversation and am closing this one.
