### ISSUE TITLE
Stop allowing the ability to set maxDuration timeout in Sauce Labs

### ISSUE THREAD

**Issue by nadvolod** [saucelabs/simple_sauce#18]
I propose to stop allowing **maxDuration** timeout to be increased by anyone using Sauce. This option leads to nothing good in my opinion and only creates future issues. It might be an immediate fix for the client’s needs. But it will ultimately be part of their demise once they come back complaining of slowness. 
So I was thinking, in one of the binding versions, what if we stopped allowing people to set the maxDuration capability. It’s default is 30 min. That’s more than plenty for a test. If they need longer, they have no choice but to break up their tests :slightly_smiling_face:
I bet we’ll get a lot of complaints in the beginning. But I think the conversations that we will have as a result will be the conversations that we would have had regardless. However, we will have these conversations earlier, before they have tests that are 2 hours in length. Ultimately, helping our clients to do the right thing and succeed.
And, this is really easy to implement 🥇

**Comment by titusfortner** [comment]
I think I'd rather see us pull this data from data science team and have success team prioritize addressing this with clients if necessary. I'm concerned about playing Nanny with this code, vs just providing access to sauce services.

**Comment by mmillgate** [comment]
If setting maxDuration is disabled and only assumes the default 30 min, this prevents the reverse side of the argument where clients are proactive in limiting the maxDuration to say 5 minutes in-house to enforce automation standards locally, rather than allowing Sauce to set that standard.

**Comment by nadvolod** [comment]
Excellent point @mmillgate . That's actually the kind of behavior we want to encourage. Test optimization to decrease execution speed. As opposed to just constantly hiking up the maxDuration value because the test keeps becoming less efficient. Then we can allow a 
maxDuration value of 30 minutes is the default, otherwise, throw an exception if someone tries to exceed it.
And if you set a lower value, you obviously can.
Sound reasonable?

**Comment by mmillgate** [comment]
Yes sounds reasonable, I was under the impression that you weren't able to go above 30 minutes anyway as a hard fast rule enforced by Saucelabs especially in the early days of helping control cost for customers where long running tests would chew up contract minutes/money.  I agree with @titusfortner however, Saucelabs has an in-house advantage to the volume of tests to look at from a data science perspective and help guide from that angle, rather than code enforcement of the services. In my experience long running tests most commonly would tend to hit against the maxDuration when there were Saucelabs VM and SauceConnect tunnel issues rather than actual long running test scenarios.  As described here: https://wiki.saucelabs.com/display/DOCS/Test+Configuration+Options#TestConfigurationOptions-MaximumTestDuration
I don't understand why anyone would want to go up to 10800 seconds, how would one even troubleshoot the problems with such a long running tests, let alone the 30 minutes durations?  YIKES!

**Comment by nadvolod** [comment]
@mmillgate appreciate your input. Unfortunately, we still have customers running such long tests. We have a few for whom 3 hours isn't enough. And we have plenty who exceed the 30 minute time out. I don't have data on this, but from my experience, this is what I can say.
I recently had a client that wanted to test a video streaming service by running several 3-hour tests on Sauce Labs and regularly checking that the video was streaming 😭

I 100% agree with you on the YIKES! And unfortunately, as the support, we then have to have conversations with the customers that they don't want such long-running tests. At this point, we face a few challenges:
1. Sometimes they're not convinced and believe that they need 45 minutes of setup in order to test a single feature on page 100 of their app. In which case we waste time talking about this and the customer just chooses to proceed in increasing their test times until they hit the 3-hour mark.
2. Even if they are convinced, they now need to refactor their 3-hourlong test to break it down into many small ones. Which is wise, but extra effort that I believe could have been avoided earlier.

Hence, my reasoning for my implementation is:

- Let's have the conversation earlier about why you need to have a test running for so long. Meaning, the conversation will happen at 30 minutes, rather than at 45 or 60 or 3 hours. And when changes need to happen, they're less painful

- I'm also a strong believer that we are a group of experts that for the majority, know what is best for the client. Not always of course, but in this case, it's hard to argue against this. So I believe in forcing the right implementation on the user. I like to take the Apple mentality. Versus Android or Windows mentality.

Let me know your thoughts 👍

**Comment by nadvolod** [comment]
Resolved [here](https://github.com/saucelabs/simple_sauce/pull/57)
