### ISSUE TITLE
it 'uses username and access key if ENV variables are defined'

### ISSUE THREAD

**Issue by nadvolod** [saucelabs/simple_sauce#19]
@titusfortner This spec is not clear, which user name and access key? The user will set it?
I would rather throw an exception if the Environment variables aren't set and not allow the user to set them directly through the code

**Comment by titusfortner** [comment]
I have in the past used a secret file that was in .gitignore and couldn't be checked in that stored sensitive info...

I guess we could have them set ENV instead of passing it into class... Java would have to also check system properties since it can't change env in code.

**Comment by nadvolod** [comment]
@titusfortner so are we good with forcing users to set environment variables? Otherwise, Runtime exception. It's a best practice, I see no reason with not forcing users into it.

**Comment by titusfortner** [comment]
I think what we agreed to in the PRs above is good to close this out.
