### ISSUE TITLE
Need to set Sauce Environment variables in Travis CI build so that our Acceptance tests can pass

### ISSUE THREAD

**Issue by nadvolod** [saucelabs/simple_sauce#24]
I think we can just use some common Sauce user

**Comment by joshmgrant** [comment]
These values were set using the `sauce_examples` user and environment variables have been added to the Travis project. In the future, we can also add [encrypted keys to the Travis config file](https://docs.travis-ci.com/user/environment-variables/#defining-encrypted-variables-in-travisyml) if necessary.
