### ISSUE TITLE
macOS 10.15 needs to be added as an allowed platform

### ISSUE THREAD

**Issue by nadvolod** [saucelabs/simple_sauce#250]
Currently getting the following error

`com.saucelabs.saucebindings.InvalidSauceOptionsArgumentException: macOS 10.15 is not a valid SaucePlatform, please choose from: [macOS 10.12, Windows 8...`

**Comment by jjathman** [comment]
It looks like it was added as a version to their main branch a while ago. Can we get a release? Ideally with Big Sur as an option as well?

**Comment by nadvolod** [comment]
@titusfortner please, the people are waiting 😂

**Comment by nadvolod** [comment]
@titusfortner I created https://github.com/saucelabs/sauce_bindings/pull/252 just needs your review and a push to Maven Central
