### ISSUE TITLE
Add Latest OS Options 

### ISSUE THREAD

**Issue by jjathman** [saucelabs/simple_sauce#277]
It looks like the `SauceBindings` has not been updated with Windows 11 or macOS Monterey, could those be added as options as they are supported by SauceLabs now?

**Comment by nadvolod** [comment]
@jjathman for sure! 
@titusfortner I wonder if we should add an overloaded method to allow users to pass in a string version of OS as a backup? This way if we are behind the ball on adding an enum, the users can at least use the string version?
Or maybe, we make the addition of these capabilities easy such as putting it into a config and then users can create a quick PR to update it?

**Comment by titusfortner** [comment]
Merged. Will get a release out soon.

**Comment by titusfortner** [comment]
#280

**Comment by nadvolod** [comment]
@titusfortner what do you think about my comment here? https://github.com/saucelabs/sauce_bindings/issues/277#issuecomment-1047328981 . It's not the first time that we've been slower to keep up with a new os version

**Comment by titusfortner** [comment]
Ah, thanks, the mechanism is actually there for working with serialized data, it's just currently private on a per capability basis. Let's discuss this option more.
