### ISSUE TITLE
Set Safai() default to Mojave and Version 12.0

### ISSUE THREAD

**Issue by nadvolod** [saucelabs/simple_sauce#28]
Safari doesn't allow us to run on "latest". Hence, we need a default for when someone wants to do:
`sauceSessions.withSafari().start();`
That default should be Mojave and Safari version 12.

@titusfortner let me know your thoughts ^^

**Comment by nadvolod** [comment]
Java implements this

**Comment by titusfortner** [comment]
Ugh, this is what I get for not looking at this closer, we can't put a default on here that overrides previous inputs or requires a specific order of operations.

**Comment by titusfortner** [comment]
Replacing this with #141
