### ISSUE TITLE
Add tunnelOwner option

### ISSUE THREAD

**Issue by brice** [saucelabs/simple_sauce#299]
I want to know if it's possible to add a tunnelOwner options that allows to use a tunnel from a different user ? 

Documentation : 
https://docs.saucelabs.com/dev/test-configuration-options/#tunnelowner

**Comment by nadvolod** [comment]
@brice thank you, we'll look at this. Which programming language are you using?

**Comment by brice** [comment]
I use Python and I created this PR #300

**Comment by waggledans** [comment]
Currently, the following is available in [python/saucebindings/configs.py](https://github.com/saucelabs/sauce_bindings/blob/main/python/saucebindings/configs.py#L9-L10):
    ```
        'tunnel_identifier': 'tunnelIdentifier',
        'parent_tunnel': 'parentTunnel'
    ```

it could be replaced with:

    ```
        'tunnel_name': 'tunnelName',
        'tunnel_owner: 'tunnelOwner'
    ```

`tunnel_owner` is equivalent to `parent_tunnel` and `tunnel_identifier` is equivalent to `tunnel_name`. [Sauce Labs docs](https://docs.saucelabs.com/dev/test-configuration-options/#parenttunnel) contain a deprecation notice In the future, only `tunnelName`/`tunnelOwner` will be supported
