### ISSUE TITLE
Build Failure in Travis CI

### ISSUE THREAD

**Issue by nadvolod** [saucelabs/simple_sauce#36]
Getting this error in Travis CI. I'm not good enough with Java to understand what it means or how to fix it. Requesting help:
https://travis-ci.org/saucelabs/simple_sauce/builds/592674082?utm_source=github_status&utm_medium=notification

Not sure if @joshmgrant or @TheTestLynx knows how to fix it?

1 error
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  01:59 min
[INFO] Finished at: 2019-10-02T17:14:21Z
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:2.10.3:jar (attach-javadocs) on project simple_sauce: MavenReportException: Error while generating Javadoc: 
[ERROR] Exit code: 1 - javadoc: error - The code being documented uses modules but the packages defined in http://docs.oracle.com/javase/8/docs/api/ are in the unnamed module.
[ERROR] 
[ERROR] Command line was: /usr/local/lib/jvm/openjdk11/bin/javadoc @options @packages
[ERROR] 
[ERROR] Refer to the generated Javadoc files in '/home/travis/build/saucelabs/simple_sauce/java/target/apidocs' dir.
[ERROR] 
[ERROR] -> [Help 1]

**Comment by TheTestLynx** [comment]
It seems to me something related to maven (I have never used it). I see java is openjdk11 , maybe this is the issue? https://github.com/joel-costigliola/assertj-core/issues/1403 Is there a way of specifying the javadocs to be 8 in the configuration as indicated? Otherwise, any chances you can revert to a previous java?

**Comment by nadvolod** [comment]
No idea @TheTestLynx :( I wasn't sure of your Java knowledge. But you're probably on my Java level, not sure what's going on haha. We'll stick to C# then and let @joshmgrant figure it out 👍

**Comment by joshmgrant** [comment]
I'm looking into this. I do think it's a JDK bug or issue on Travis but I'll confirm. 

Also, I would like our CI to work where each language executes tests in parallel but each test suite needs to pass to get a passing build. If @nadvolod or @TheTestLynx wants to dig into Travis to see how this may be done, please go ahead! :)

**Comment by joshmgrant** [comment]
Fixed in #38

**Comment by TheTestLynx** [comment]
@joshmgrant someday, eventually, taking a note of it

**Comment by joshmgrant** [comment]
@TheTestLynx I actually just implemented this! It turns out TravisCI does support this. Take a look at the latest .travis.yml file to see :)
