### ISSUE TITLE
Fix some or all TODOs in Java bindings

### ISSUE THREAD

**Issue by nadvolod** [saucelabs/simple_sauce#46]
There are a bunch of minor TODO comments in the Java bindings that can be fixed to make the code cleaner and more understandable

**Comment by picimako** [comment]
Hi @nadvolod,
I wanted to work on this issue, however it seems that there are no TODO comments in the Java bindings, at least I couldn't find any.  :)

**Comment by nadvolod** [comment]
Hey @picimako super happy that you're looking to help out here 👍 Yea, we went through quiet a refactoring period that probably rendered this issue and other's obsolete. Let me clean up here and see where we can take your help

**Comment by nadvolod** [comment]
@picimako did you want to take a stab at https://github.com/saucelabs/sauce_bindings/issues/144 or https://github.com/saucelabs/sauce_bindings/issues/145 ?

**Comment by picimako** [comment]
@nadvolod I'm happy to help. :)
I'm looking into the issues you mentioned.
