### ISSUE TITLE
Add CI System

### ISSUE THREAD

**Issue by nadvolod** [saucelabs/simple_sauce#6]
No clue how this would work for a mono repo

**Comment by nadvolod** [comment]
@andrewmkrug hey bro, this would be a really awesome thing if you want to tackle it? It will make sure that we're having CI on all of the code and not breaking stuff. We had Travis CI set up before. Let me know what you think...

**Comment by nadvolod** [comment]
@andrewmkrug hey bud, did you have a chance to look at this?

**Comment by joshgrantsauce** [comment]
Addressed in #21
