### ISSUE TITLE
Add parallel test execution to the Java framework

### ISSUE THREAD

**Issue by nadvolod** [saucelabs/simple_sauce#7]

**Comment by titusfortner** [comment]
What are you thinking for this? I think the best practice answer is for teams to use Maven, so curious what you wanted in the code.

**Comment by nadvolod** [comment]
@titusfortner sorry for the lack of clarity here. I was talking about making all the unit tests inside of the bindings run in parallel. I know I need to add like Surefire to the pom.xml. So I was making a note to myself to do that. Nothing related to the binding specs

**Comment by nadvolod** [comment]
Complete [here](https://github.com/saucelabs/simple_sauce/pull/54)
