### ISSUE TITLE
Remove duplication in the setUp of the SauceSessionTest.java

### ISSUE THREAD

**Issue by nadvolod** [saucelabs/simple_sauce#71]
There is duplication in the `SauceSessionTest.java` here https://github.com/saucelabs/simple_sauce/blob/5ec70f995f6661a168c65bad224ec93c17b11705/java/src/test/java/com/saucelabs/simplesauce/SauceSessionTest.java#L21
. That duplication also lives in `BaseConfigurationTest.java`. They can be combined and cleaned up.

**Comment by picimako** [comment]
Hi @nadvolod,
As I see `BaseConfigurationTest` was removed in https://github.com/saucelabs/sauce_bindings/commit/0cac22328962bcdfaad168a8c28390479ea4ae87

Is there any task left on this issue?

**Comment by nadvolod** [comment]
@picimako thanks for you desire to help. Let me do a bit of clean up here and let's see where we can take your assistance 👍
